#!/bin/bash
if [ -z "$1" ]; then 
  echo usage: $0 jvmName
  exit
 fi
java -ea -cp 'jars/*' -Djava.security.manager -Djava.security.policy=assembly.policy fr.upmc.components.examples.basic_cs.DistributedAssembly $1 config.xml